services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tornear-api
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run start-local
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./initDatabase:/docker-entrypoint-initdb.d
